[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

# use [espflash](https://github.com/esp-rs/espflash) to flash and monitor
runner = "espflash flash --monitor"

# alternatively, you can flash with your browser
# via [web-flash](https://github.com/esp-rs/esp-web-flash-server)
# runner = "web-flash --chip=esp32 "

rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.3"
